- name: Find all templates on node
  community.general.proxmox_vm_info:
    type: qemu
    node: "{{ host_node }}"
    api_user: "{{ proxmox.api.user.full_name }}"
    api_token_id: "{{ proxmox.api.token.id }}"
    api_token_secret: "{{ proxmox.api.token.secret }}"
    api_host: "{{ inventory_hostname }}"
  register: template_info

# TODO clean templates not defined
