- name: Try to create a VM in proxmox
  block:
    - name: Setup VM in proxmox
      throttle: 1
      community.general.proxmox_kvm:
        clone: "{{ host.clone }}"
        name: "{{ playbook_hostname }}"
        newid: "{{ host.vm_id | default(omit) }}"
        memory: "{{ host.memory | default('4096') }}"
        cores: "{{ host.cores | default('2') }}"
        storage: "{{ host.storage | default(omit) }}"
        nameservers: "{{ host.nameservers | default(omit) }}"
        searchdomains: "{{ host.searchdomains | default(omit) }}"
        timeout: "{{ host.timeout | default(300) }}"
        node: "{{ host.node }}"
        full: "{{ host.full_clone | default(false) }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        state: present
      register: created_vm

    - name: Update hardwarde parameters
      community.general.proxmox_kvm:
        name: "{{ playbook_hostname }}"
        timeout: "{{ proxmox.api.timeout | default(300) }}"
        node: "{{ host.node }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        memory: "{{ host.memory | default('4096') }}"
        cores: "{{ host.cores | default('2') }}"
        update: true
      ignore_errors: true

    - name: Configure cloud init parameters
      community.general.proxmox_kvm:
        name: "{{ playbook_hostname }}"
        timeout: "{{ proxmox.api.timeout | default(300) }}"
        node: "{{ host.node }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        autostart: "{{ host.autostart | default(true)  }}"
        ciuser: "{{ host.user }}"
        cipassword: "{{ host.password }}"
        sshkeys: "{{ host.sshkeys | default(omit) }}"
        net:
          net0: "virtio,bridge={{ host.bridge | default('vmbr0') }},tag=77" 
        ipconfig:
          ipconfig0: "ip={{ host.ipv4 }}/{{ host.subnet }},gw={{ host.gateway }}" 
        update: true
    
    - name: Start VM in proxmox
      community.general.proxmox_kvm:
        name: "{{ playbook_hostname }}"
        timeout: "{{ proxmox.api.timeout | default(300) }}"
        node: "{{ host.node }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        state: started

    - name: Register hostname at DNS server
      include_role:
        name: powerdns
        tasks_from: create_record
      when: playbook_hostnameservers is defined

    - name: Retrieve info about VM in proxmox
      community.general.proxmox_vm_info:
        name: "{{ playbook_hostname }}"
        node: "{{ host.node }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
      register: proxmox_vm_info

    - name: Wait for the machine to come online
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 600
      when: created_vm.changed

    - name: Wait for ssh to become available
      ansible.builtin.wait_for:
        port: 22
        sleep: 10
        delay: 30
        host: "{{ host.ipv4 }}"
      when: created_vm.changed
    
    - name: Write the new VM instance host key to known hosts
      connection: local
      ansible.builtin.shell: "ssh-keyscan -H {{ host.ipv4 }} >> ~/.ssh/known_hosts"
      when: created_vm.changed
  rescue:
    - name: Remove VM from proxmox
      community.general.proxmox_kvm:
        name: "{{ playbook_hostname }}"
        node: "{{ host.node }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        force: true
        state: absent
