- name: "Setup zone {{ host_zone}}"
  ansible.builtin.command: >
    pdnsutil create-zone "{{ host_zone }}"
  when: dns in group_names

# Otherwise use api from dns server
- name: Create dns zone
  ansible.builtin.uri:
    url: "http://{{ item }}:{{ dns.port | default(8081) }}/api/v1/servers/localhost/zones"
    method: POST
    body: "{{ lookup('ansible.builtin.template','zone.json.j2') }}"
    body_format: json
    headers:
      X-API-Key: "{{ dns.api_key }}"
  when: dns not in group_names
  loop: "{{ host_nameservers }}"