# When executing on powerdns use pdnsutil
- name: "Add record {{ host_zone}} with pdnsutil"
  ansible.builtin.command: >
    pdnsutil add-record {{ host_zone }} {{ host_name }} A {{ host_ipv4 }}
  when: dns in group_names

# Otherwise use api from dns server
- name: "Create dns record with powerdns api"
  ansible.builtin.uri:
    url: "http://{{ item }}:8081/api/v1/servers/localhost/zones/{{ host_zone }}."
    method: PATCH
    body: "{{ lookup('ansible.builtin.template','record.json.j2') }}"
    body_format: json
    headers:
      X-API-Key: "{{ dns.api.key }}"
    status_code: [200, 204, 201]
  when: dns not in group_names and host_nameservers
  loop: "{{ host_nameservers }}"