# When executing on powerdns use pdnsutil
- name: "Add record {{ host.zone}} with pdnsutil"
  ansible.builtin.command: >
    pdnsutil add-record {{ host.zone }} {{ host.name }} A {{ host.ipv4 }}
  when: dns in group_names

# Otherwise use api from dns server
- name: "Create dns record {{ host.name }}.{{ host.zone }} with powerdns api"
  ansible.builtin.uri:
    url: "http://{{ item }}:8081/api/v1/servers/localhost/zones/{{ host.zone }}."
    method: PATCH
    body: "{{ lookup('ansible.builtin.template','record.json.j2') }}"
    body_format: json
    headers:
      X-API-Key: "{{ dns.api.key }}"
    status_code: [200, 204, 201]
  when: dns not in group_names and host.nameservers
  loop: "{{ host.nameservers }}"