- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ fileshare.path }}" 
    state: directory
  become: true
  delegate_to: "{{ fileshare.host }}"

# NFS runs everything as nobody:nogroup
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ fileshare.path }}"
    owner: "{{ host_user | default(nobody) }}"
    group: "{{ host_user | default(nogroup) }}"
    mode: '0644'
  become: true
  delegate_to: "{{ fileshare.host }}"

- name: Add directory to exported
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: '^{{ fileshare.path }} '
    line: "{{ fileshare.path }}    {{ host_subnet_cidr }}(rw,sync,no_root_squash,no_subtree_check)"
  become: true
  delegate_to: "{{ fileshare.host }}"

- name: Restart nfs server
  ansible.builtin.systemd_service:
    state: restarted
    name: nfs-kernel-server 
  become: true
  delegate_to: "{{ fileshare.host }}"
