- name: "Install nfs client packages"
  ansible.builtin.import_tasks:
    file: client.yml
  become: true

- name: "Create fileshares on remote"
  ansible.builtin.include_tasks:
    file: create_share.yml
  loop: "{{ host_fileshares }}" 
  loop_control:
    loop_var: fileshare

- name: "Create fileshare folders"
  ansible.builtin.file:
    path: "{{ fileshare.local_path }}" 
    mode: '0777'
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    state: directory
  loop: "{{ host_fileshares }}" 
  loop_control:
    loop_var: fileshare
  become: true

- name: "Write shares in fstab"
  ansible.posix.mount:
    src: "{{ fileshare.host }}:{{ fileshare.remote_path }}"
    path: "{{ fileshare.local_path }}" 
    opts: rw,sync,hard
    boot: true
    state: mounted
    fstype: nfs
  become: true
  loop: "{{ host_fileshares }}" 
  loop_control:
    loop_var: fileshare