- name: Install sabnzb
  block:
    - name: Add sabnzb repository
      ansible.builtin.apt_repository:
        repo: ppa:jcfp/nobetas

    - name: Update apt packages
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: true

    - name: Install sabnzb package
      ansible.builtin.apt:
        name: sabnzbdplus

    - name: Create sabnzb config directory
      ansible.builtin.file:
        path: "/home/{{ host_user }}/.sabnzbd" 
        state: directory

    - name: Create sabnzb config
      ansible.builtin.template:
        src: sabnzbd.ini.j2
        dest: "/home/{{ host_user }}/.sabnzbd/sabnzbd.ini"

    - name: Start sabnzbd service
      ansible.builtin.systemd_service:
        name: sabnzbdplus
        enabled: true
        state: started
  become: true