- name: Install sabnzb
  block:
    - name: Add sabnzb repository
      ansible.builtin.apt_repository:
        repo: ppa:jcfp/nobetas

    - name: Update apt packages
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: true

    - name: Install sabnzb package
      ansible.builtin.apt:
        name: sabnzbdplus

    - name: Create sabnzb config directory
      ansible.builtin.file:
        path: "/home/{{ host_user }}/.sabnzbd" 
        state: directory
      become_user: "{{ host_user }}"
      become: false

    - name: Create /etc/default/sabnzbdplus
      ansible.builtin.template:
        src: sabnzbdplus.j2
        dest: /etc/default/sabnzbdplus

    - name: Start sabnzbd service
      ansible.builtin.systemd_service:
        name: sabnzbdplus
        enabled: true
        state: started
    
    - name: Add host to whitelist
      ansible.builtin.lineinfile:
        path: "/home/{{ host_user }}/.sabnzbd/sabnzbd.ini"
        line: "host_whitelist = {{ host_name }}.{{ host_zone }}" 
        search_string: "host_whitelist ="
        create: true
      register: sabnzb_add_host_to_whitelist

    - name: Restart sabnzb service
      ansible.builtin.systemd_service:
        name: sabnzbdplus
        state: restarted
      when: sabnzb_add_host_to_whitelist.changed
  become: true