- name: Generate ssh key path
  ansible.builtin.set_fact:
    ssh_key_path: "/home/{{ host_user }}/.ssh/{{ host_ssh_key_name }}"
    ssh_public_key_path: "/home/{{ host_user }}/.ssh/{{ host_ssh_key_name }}.pub"

- name: Retrieve ssh key
  ansible.builtin.stat:
    path: "{{ ssh_key_path }}"
  register: public_key 

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_path }}" 
  when: not public_key.stat.exists

- name: Slurp the content of the public key
  ansible.builtin.slurp:
    src: "{{ ssh_public_key_path }}"
  register: ssh_public_key

- name: Get content of public ssh key
  ansible.builtin.set_fact:
    public_key_content: "{{ ssh_public_key.content | ansible.builtin.b64decode }}"

- name: Add public key to authorized keys of remotes
  ansible.builtin.lineinfile:
    path: "/home/{{ host_user }}/.ssh/authorized_keys"
    line: "{{ public_key_content }}" 
    search_string: "{{ public_key_content }}"
  when:
    - host_fileshares is defined
  loop: "{{ host_fileshares }}"
  loop_control:
    loop_var: fileshare
  delegate_to: "{{ fileshare.host }}"