- name: Populate service facts
  service_facts:

- name: Update DNS config for systemd-resolved
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  when: '"systemd-resolved.service" in services'

- name: Check if /etc/resolv.conf is correctly linked
  ansible.builtin.stat:
    path: /etc/resolv.conf
  register: resolv_conf
  when:
    - '"systemd-resolved.service" in services'

- name: Link resolv.conf to resolved.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    force: true
    state: link
  when: 
    - '"systemd-resolved.service" in services'
    - '"stub-resolv.conf" in resolv_conf.stat.lnk_target'

- name: Restart systemd-resolved service 
  ansible.builtin.systemd_service:
    state: restarted 
    name: systemd-resolved
  when: '"systemd-resolved.service" in services'