- name: Install rancher server 
  ansible.builtin.import_tasks: install_rke2_server.yml
  become: true
  when: '"server" in inventory_hostname' 

- name: Retrieve server token from {{ rancher_server }}
  ansible.builtin.slurp: 
    src: /var/lib/rancher/rke2/server/node-token
  become: true
  delegate_to: "{{ rancher_server }}"
  register: rke_server_token_slurp
  when: '"agent" in inventory_hostname' 

- name: Register server token from {{ rancher_server }}
  ansible.builtin.set_fact: 
    rke_server_token: "{{ rke_server_token_slurp['content'] | b64decode }}"
  when: '"agent" in inventory_hostname' 

- name: Install rancher agent 
  ansible.builtin.import_tasks: install_rke2_agent.yml
  become: true
  when: '"agent" in inventory_hostname' 