- name: Update apt packages
  ansible.builtin.apt:
     cache_valid_time: 3600
     update_cache: true

- name: Search apt cache for major docker version
  ansible.builtin.shell:
    cmd: apt-cache madison docker-ce | awk '{ print $3 }' | grep {{ docker.version|quote }} | head -n 1
  register: docker_version_output

- name: Set docker version variable
  ansible.builtin.set_fact:
    docker_version: "{{ docker_version_output.stdout }}"

- name: Install major docker version
  ansible.builtin.apt:
    pkg:
      - "docker-ce={{ docker_version }}"
      - "docker-ce-cli={{ docker_version }}"
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin 
    allow_downgrade: true

- name: Add user to docker group
  ansible.builtin.user:
     name: "{{ user }}" 
     append: true
     groups: 
       - docker
