- name: Setup NFS and create mounts 
  include_role:
    name: nfs

- name: Start watchtower docker container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: "always"
    state: started

- name: Start Plex Docker container
  community.docker.docker_container:
    name: plex 
    image: lscr.io/linuxserver/plex:latest
    volumes:
      - ~/config/plex:/config
      - ~/plex/media/tv:/tv
      - ~/plex/media/movies:/movies 
    restart_policy: "always"
    state: started
    ports:
      - 32400:32400

- name: Start sonarr docker container
  community.docker.docker_container:
    name: sonarr 
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - ~/config/sonarr:/config
    ports:
      - 8989:8989 
    restart_policy: "always"
    state: started

- name: start radarr docker container
  community.docker.docker_container:
    name: radarr 
    image: lscr.io/linuxserver/radarr:latest
    volumes:
      - ~/config/radarr:/config
    ports:
      - 7878:7878
    restart_policy: "always"
    state: started

- name: start overseerr docker container
  community.docker.docker_container:
    name: overseerr 
    image: sctx/overseerr
    env:
      TZ: Europe/Amstedam
    volumes:
      - ~/config/overseerr:/app/config
    ports:
      - 5055:5055
    restart_policy: "always"
    state: started