- name: Setup NFS and create mounts 
  include_role:
    name: nfs

- name: Start watchtower docker container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: "always"
    state: started

- name: Start Plex Docker container
  community.docker.docker_container:
    name: plex 
    image: lscr.io/linuxserver/plex:latest
    volumes:
      - /path/to/plex/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies 
    restart_policy: "always"
    state: started
    ports:
      - 32400:32400

- name: Start sonarr docker container
  community.docker.docker_container:
    name: sonarr 
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - /path/to/sonarr/data:/config
    ports:
      - 8989:8989 
    restart_policy: "always"
    state: started

- name: start radarr docker container
  community.docker.docker_container:
    name: radarr 
    image: lscr.io/linuxserver/radarr:latest
    volumes:
      - /path/to/radarr/data:/config
    ports:
      - 7878:7878
    restart_policy: "always"
    state: started
