- name: Setup VM in proxmox for rancher servers
  hosts: rancher_server
  gather_facts: false
  roles:
    - role: gijsentius.homelab.proxmox
      delegate_to: localhost
      connection: local
  when: host_type == "vm"

- name: Setup VM in proxmox for rancher agents 
  hosts: rancher_agent
  gather_facts: false
  roles:
    - role: gijsentius.homelab.proxmox
      delegate_to: localhost
      connection: local
  when: host_type == "vm"

- name: Setup rancher servers
  hosts: rancher_server
  roles:
    - role: gijsentius.homelab.common
    - role: gijsentius.homelab.rancher 

- name: Setup rancher agents 
  hosts: rancher_agent
  roles:
    - role: gijsentius.homelab.common
    - role: gijsentius.homelab.rancher 

- name: Install essentials rancher components
  hosts: rancher_server
  gather_facts: true
  tasks:
    - name: Install automatic cluster upgrades
      ansible.builtin.include_role:
        name: gijsentius.homelab.rancher
        tasks_from: install_system-upgrade-controller.yml

