- name: Setup VM in proxmox for plex 
  hosts: plex
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost
  tags: 
    - proxmox
    - plex-setup

- name: Setup VM in proxmox for sabnzb 
  hosts: sabnzb
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost
  tags: 
    - proxmox

- name: Setup VM in proxmox for qbittorrent 
  hosts: qbittorrent
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost
  tags: 
    - proxmox

- hosts: plex
  gather_facts: true
  roles:
    - role: common
    - role: docker
  tags: plex-setup

- hosts: plex
  gather_facts: true
  roles:
    - role: plex
  tags: plex

- hosts: sabnzb
  gather_facts: true
  roles:
    - role: common
    - role: sabnzb
  tags: sabnzb

- hosts: qbittorrent 
  gather_facts: true
  roles:
    - role: common
    - role: docker
    - role: qbittorent 
  tags: qbittorrent