- name: Setup VM in proxmox for caddy 
  hosts: caddy 
  tags: setup
  gather_facts: false
  roles:
    - role: gijsentius.homelab.proxmox 
      delegate_to: localhost

- name: Install and configure caddy
  hosts: caddy 
  tags: config
  gather_facts: true
  roles:
    - role: gijsentius.homelab.common
    - role: gijsentius.homelab.caddy 
