- name: Setup VM in proxmox for plex 
  hosts: plex
  gather_facts: false
  roles:
    - role: gijsentius.homelab.proxmox 
      delegate_to: localhost
  tags: 
    - proxmox
    - plex-setup

- name: Setup VM in proxmox for sabnzb 
  hosts: sabnzb
  gather_facts: false
  roles:
    - role: gijsentius.homelab.proxmox 
      delegate_to: localhost
  tags: 
    - proxmox

- name: Setup VM in proxmox for qbittorrent 
  hosts: qbittorrent
  gather_facts: false
  roles:
    - role: gijsentius.homelab.proxmox 
      delegate_to: localhost
  tags: 
    - proxmox

- hosts: plex
  gather_facts: true
  roles:
    - role: gijsentius.homelab.common
    - role: gijsentius.homelab.docker
  tags: plex-setup

- hosts: plex
  gather_facts: true
  roles:
    - role: gijsentius.homelab.plex
  tags: plex

- hosts: sabnzb
  gather_facts: true
  roles:
    - role: gijsentius.homelab.common
    - role: gijsentius.homelab.sabnzb
  tags: sabnzb

- hosts: qbittorrent 
  gather_facts: true
  roles:
    - role: gijsentius.homelab.common
    - role: gijsentius.homelab.docker
    - role: gijsentius.homelab.qbittorrent 
  tags: qbittorrent
