- name: Setup VM in proxmox for rancher servers
  hosts: rancher_server
  gather_facts: false
  roles:
    - role: proxmox
      delegate_to: localhost

- name: Setup rancher servers
  hosts: rancher_server
  roles:
    - role: rancher 

- name: Setup VM in proxmox for rancher agents 
  hosts: rancher_agent
  gather_facts: false
  roles:
    - role: proxmox
      delegate_to: localhost

- name: Setup rancher agents 
  hosts: rancher_agent
  roles:
    - role: rancher 