- name: Setup VM in proxmox for plex 
  hosts: plex
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost
  tags: plex

- name: Setup VM in proxmox for sabnzb 
  hosts: sabnzb
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost
  tags: sabnzb

- name: Setup VM in proxmox for qbittorrent 
  hosts: qbittorrent
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost
  tags: qbittorrent

- hosts: plex
  gather_facts: true
  roles:
    - role: common
    - role: docker
    - role: plex
  tags: plex

- hosts: sabnzb
  gather_facts: true
  roles:
    - role: common
    - role: sabnzb
  tags: sabnzb

- hosts: qbittorrent 
  gather_facts: true
  roles:
    - role: common
    - role: docker
    - role: qbittorent 
  tags: qbittorrent