- hosts: powerdns 
  gather_facts: false
  roles:
    - role: proxmox
      delegate_to: localhost
      connection: local

- hosts: powerdns
  gather_facts: true
  roles:
    - role: common
    - role: docker
    - role: powerdns
