- hosts: powerdns 
  gather_facts: false
  roles:
    - role: gijsentius.homelab.proxmox
      delegate_to: localhost
      connection: local

- hosts: powerdns
  gather_facts: true
  roles:
    - role: gijsentius.homelab.common
    - role: gijsentius.homelab.docker
    - role: gijsentius.homelab.powerdns
