- name: Setup VM in proxmox for plex 
  hosts: plex
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost

- name: Setup VM in proxmox for sabnzb 
  hosts: sabnzb
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost

- name: Setup VM in proxmox for qbittorrent 
  hosts: qbittorrent
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost

- hosts: plex
  gather_facts: true
  roles:
    - role: common
    - role: docker
    - role: plex

- hosts: sabnzb
  gather_facts: true
  roles:
    - role: common
    - role: sabnzb

- hosts: qbittorrent 
  gather_facts: true
  roles:
    - role: common
    - role: docker
    - role: qbittorent 