- name: Setup VM in proxmox for vaultwarden
  hosts: vault 
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost

- name: Run common tasks
  hosts: filestore
  gather_facts: true
  roles:
    - common

- name: Start vaultwarden on VM inside docker container
  hosts: vault
  gather_facts: true
  tasks:
    - name: Setup docker on newly created VM
      include_role:
        name: docker

    - name: Start vaultwarden in Docker container
      community.docker.docker_container:
        name: vaultwarden
        image: vaultwarden/server:latest
        volumes:
          - "/home/{{ lookup('env', 'USER') }}/vw-data/:/data/"
        ports:
          - "0.0.0.0:8080:80"
        restart_policy: "always"
        state: started


