- name: Setup VM in proxmox for vaultwarden
  hosts: vault 
  gather_facts: false
  roles:
    - role: gijsentius.homelab.proxmox 
      delegate_to: localhost

- name: Run common tasks
  hosts: vault
  gather_facts: true
  roles:
    - gijsentius.homelab.common

- name: Start vaultwarden on VM inside docker container
  hosts: vault
  gather_facts: true
  tasks:
    - name: Create snapshot of VM
      ansible.builtin.include_role:
        name: gijsentius.homelab.proxmox
        tasks_from: add_snapshot.yml
      when: host_snapshot
    
    - name: Setup docker on newly created VM
      ansible.builtin.include_role:
        name: docker

    - name: Start vaultwarden in Docker container
      community.docker.docker_container:
        name: vaultwarden
        image: vaultwarden/server:latest
        volumes:
          - "/home/{{ lookup('env', 'USER') }}/vw-data/:/data/"
        ports:
          - "0.0.0.0:8080:80"
        restart_policy: "always"
        state: started

    - name: Start watchtower docker container
      community.docker.docker_container:
        name: watchtower
        image: containrrr/watchtower:latest
        env:
          TZ: Europe/Amsterdam
          PUID: '1000'
          PGID: '1000'
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: "always"
        state: started

