- name: Setup VM in proxmox for rancher servers
  hosts: rancher-server
  gather_facts: false
  roles:
    - role: proxmox
      delegate_to: localhost

- name: Setup VM in proxmox for rancher servers
  hosts: rancher-server
  roles:
    - role: rancher 

- name: Setup VM in proxmox for rancher agents 
  hosts: rancher-agent
  gather_facts: false
  roles:
    - role: proxmox
      delegate_to: localhost

- name: Setup VM in proxmox for rancher agents 
  hosts: rancher-agent
  roles:
    - role: rancher 