- name: Setup VM in proxmox for filestore
  hosts: filestore 
  gather_facts: false
  roles:
    - role: proxmox
      delegate_to: localhost

- name: Run common tasks
  hosts: filestore
  gather_facts: true
  roles:
    - common

- name: Setup NFS server
  hosts: filestore
  gather_facts: true 
  tasks:
    - name: Configure nfs on VM 
      include_role:
        name: nfs
        tasks_from: server.yml 