- name: Setup VM in proxmox for plex 
  hosts: plex
  gather_facts: false
  roles:
    - role: proxmox 
      delegate_to: localhost

- hosts: plex
  gather_facts: true
  roles:
    - role: common
    - role: docker
    - role: plex